version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update
      - sudo apt-get install terraform  
      - terraform -version
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
    commands:
      
  post_build:
    commands:
    